### PR TITLE
F opus featuremodel

### PR DESCRIPTION
**Pull request by Zatho**
Quick Pull-Request so Florian can have a look at my FeatureModel and find possible errors.

### CODE REVIEW

**Review by ChristianKaltenecker — COMMENTED** [review]
Just a quick question before approval:
Is there a specific reason for using the files in the `tests` directory?

Besides that, it looks good to me.

**Comment by ChristianKaltenecker** [comment]
I just want to remind you that this Pull Request is still open.

**Comment by Zatho** [comment]
Sorry, didn't see this was still open Christian.
I tested a couple of file locations because of detection issues with the opus project. The intended locations are in [729a22a](https://github.com/se-sic/ConfigurableSystems/pull/15/commits/729a22a5461fd95c3d34242f903b64beba69ddc9)
not the latest commit. At the time I had no idea the test directory is disregarded and I played around with locations quite a bit that is most likely why they ended up here.

**Comment by ChristianKaltenecker** [comment]
All right. Thanks for the fast answer.

Will you change these locations accordingly if the test directory is disregarded?

**Comment by Zatho** [comment]
I'll have a look later today and update them again sure.

**Comment by Zatho** [comment]
I removed the test locations. The other locations look good from my side.

**Comment by ChristianKaltenecker** [comment]
Looks good to me too. Thanks for your work!

**Review by ChristianKaltenecker — APPROVED** [review]

**Comment by ChristianKaltenecker** [comment]
Maybe @vulder should also take a look on it

**Review by vulder — APPROVED** [review]

**Pull request merged**
