### PR TITLE
Added (incomplete) FM for PicoSat

### PR DESCRIPTION
**Pull request by bnico99**
Draft PR to share FeatureModel and get feedback

### CODE REVIEW

**Review by ChristianKaltenecker — COMMENTED** [review]
@vulder Is it already possible to annotate a source range with the corresponding release?

Other than that it looks good to me.

**Comment by ChristianKaltenecker** [comment]
I just looked it up. Lauritz already implemented that.
Take a look at https://github.com/se-sic/VaRA/issues/965
Could you incorporate that?
Thanks!

**Comment by bnico99** [comment]
>Could you incorporate that?

@ChristianKaltenecker Done :+1:

**Review by ChristianKaltenecker — APPROVED** [review]
Thanks for incorporating the revision ranges.

Looks good to me

**Review by vulder — APPROVED** [review]

**Pull request merged**
